// app/layout.tsx
import AuthProvider from "../components/SessionProvider";
import { ThemeProvider } from "../components/ThemeProvider";
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ClientHeader } from "@/components/ClientHeader";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        <AuthProvider>
          <ThemeProvider>
            {/* Render a separate client component for conditional rendering */}
            <ClientHeader />
            {children}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
